name: MovingShips
version: '${project.version}'
main: MovingShips.MovingShips.MovingShips
api-version: 1.19
permissions:
  movingships.admin:
    description: allows the player to move/rotate or delete a ship regardless if they own the ship or not.
    default: op
commands:
  moveship:
    description: Moves the ship.
    usage: /moveship <Forward/Back/Left/Right> <Distance> <Name of ship>
    aliases:
    permission: moveship
    permission-message: You do not have permission to move a ship.
  createship:
    description: Creates a ship.
    usage: /createship <X1> Y1> <Z1> <X2> <Y2> <Z2> <Name of ship>
    aliases:
    permission: createship
    permission-message: You do not have permission to create a ship.
  rotateship:
    description: Rotates the ship.
    usage: /rotateship <Left/Right> <Name of ship>
    aliases:
    permission: rotateship
    permission-message: You do not have permission to rotate a ship.
  setshipcontrols:
    description: Sets the ship controls.
    usage: /setshipcontrols <Forward/Back/Left/Right/RotateLeft/RotateRight> <Name of ship>
    aliases:
    permission: setshipcontrols
    permission-message: You do not have permission to set the controls of a ship.
  setshipforwarddirection:
    description: Sets the ship controls.
    usage: /setshipforwarddirection <Name of ship>
    aliases:
    permission: setshipforwarddirection
    permission-message: You do not have permission to set the forward direction of a ship.
  shipsetup:
    description: Creates a ship along with direction, control and name.
    usage: /shipsetup
    aliases:
    permission: shipsetup
    permission-message: You do not have permission to create a ship.
  deleteship:
    description: Deletes the specified ship.
    usage: /deleteship <Name of ship>
    aliases:
    permission: deleteship
    permission-message: You do not have permission to delete a ship.
  shiplist:
    description: Shows all ships in the server.
    usage: /shiplist
    aliases:
    permission: shiplist
    permission-message: You do not have permission to list all ships.
  shiphelp:
    description: Lists all ships commands.
    usage: /shiphelp
    aliases:
    permission: shiphelp
    permission-message: You do not have permission to get help.
  shipinfo:
    description: Lists all the specified ship information.
    usage: /shipinfo
    aliases:
    permission: shipinfo
    permission-message: You do not have permission to see a ships info.
