name: MovingShips
version: '${project.version}'
main: MovingShips.MovingShips.MovingShips
api-version: 1.19
permissions:
  movingships.admin:
    description: allows the player to move/rotate or delete a ship regardless if they own the ship or not.
    default: op
commands:
  moveship:
    description: Moves the ship.
    usage: /moveship <Forward/Back/Left/Right> <Distance> <Name of ship>
    aliases:
    permission: moveship
    permission-message: You do not have permission to move a ship.
  createship:
    description: Creates a ship.
    usage: /createship <X1> Y1> <Z1> <X2> <Y2> <Z2> <Name of ship>
    aliases:
    permission: createship
    permission-message: You do not have permission to create a ship.
  rotateship:
    description: Rotates the ship.
    usage: /rotateship <Left/Right> <Name of ship>
    aliases:
    permission: rotateship
    permission-message: You do not have permission to rotate a ship.
  setshipcontrols:
    description: Sets the ship controls.
    usage: /setshipcontrols <Forward/Back/Left/Right/RotateLeft/RotateRight> <Name of ship>
    aliases:
    permission: setshipcontrols
    permission-message: You do not have permission to set the controls of a ship.
  setshipforwarddirection:
    description: Sets the ship controls.
    usage: /setforwarddirection name_of_ship
    aliases:
    permission: setforwarddirection
    permission-message: You do not have permission to spawn a ship.
  setupship:
    description: Sets the ship controls.
    usage: /setupship
    aliases:
    permission: setupship
    permission-message: You do not have permission to spawn a ship.
